### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by codepathreview** [palexis3/TodoAndroidApp#1]
Hello Patrick, 

Thanks for submitting your pre-work but your current submission is incomplete. Can you please review the section in the pre-work about [the readme](http://courses.codepath.com/snippets/intro_to_android/prework#heading-4-submitting-the-project) for your project? 

In particular, be sure to use this [README template](http://courses.codepath.com/snippets/intro_to_android/readme_templates/prework_readme.md?raw=true), check off your completed features (`[x]`) and [include a recorded app walkthrough with LiceCap](http://www.cockos.com/licecap/). 
Looks like you lost a recorded app walkthrough

Please re-submit your project on your [application dashboard](https://apply.codepath.com/dashboard/) and reply back on this issue once that's completed.

**Comment by palexis3** [comment]
Hello, I have fixed the issue of "Looks like you lost a recorded app walkthrough" with my gif. If there are any issues feel free to contact me as soon as you can.
